name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements_test.txt
    - name: Lint with pre-commit
      run: |
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pytest -p no:spark -m "not spark_test"
        
  armv64_job:
      name: Build and Test for arm64
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install python3 python3-pip python3-venv curl && \
              python3 -m pip install virtualenv && python3 -m venv py38-venv && \
              source py38-venv/bin/activate && \
              python -m pip install --upgrade pip && \
              python --version && \
              uname -m && \
              whoami && \
              pwd && \
              ls && \
              apt-get -y install graphviz && \
              python -m pip install --upgrade pip && \
              pip install -r requirements.txt && \
              pip install -r requirements_dev.txt && \
              pip install -r requirements_test.txt && \
              pip install -e . && \
              pytest -p no:spark -m "not spark_test" && \
              deactivate'
